###############################################
######### Joint Trajectory Controller  ########
###############################################
VelocityControllers_JointTrajectoryController:
  type: "velocity_controllers/JointTrajectoryController"
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - joint_7

  gains: # Required because we're controlling a velocity interface
    joint_1: {p: 20,  d: 0, i: 1, i_clamp: 0}
    joint_2: {p: 20,  d: 0, i: 1, i_clamp: 0}
    joint_3: {p: 20,  d: 0, i: 1, i_clamp: 0}
    joint_4: {p: 20,  d: 0, i: 1, i_clamp: 0}
    joint_5: {p: 20,  d: 0, i: 1, i_clamp: 0}
    joint_6: {p: 20,  d: 0, i: 1, i_clamp: 0}
    joint_7: {p: 20,  d: 0, i: 1, i_clamp: 0}

robot:
  pos_corr_gain: 0 # parameter in RAPID that needs to be set to zero to accept velocity commands alone