joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: &loop_hz 100

arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints: &robot_joints
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - joint_7
  gains:
    joint_1: {p: 2000.0, i: 1, d: 20.0, i_clamp: 1}
    joint_2: {p: 2000.0, i: 1, d: 20.0, i_clamp: 1}
    joint_3: {p: 2000.0, i: 1, d: 20.0, i_clamp: 1}
    joint_4: {p: 2000.0, i: 1, d: 20.0, i_clamp: 1}
    joint_5: {p: 2000.0, i: 1, d: 20.0, i_clamp: 1}
    joint_6: {p: 2000.0, i: 1, d: 20.0, i_clamp: 1}
    joint_7: {p: 2000.0, i: 1, d: 20.0, i_clamp: 1}
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    joint_1: {trajectory: 0.05, goal: 0.05}
    joint_2: {trajectory: 0.05, goal: 0.05}
    joint_3: {trajectory: 0.05, goal: 0.05}
    joint_4: {trajectory: 0.05, goal: 0.05}
    joint_5: {trajectory: 0.05, goal: 0.05}
    joint_6: {trajectory: 0.05, goal: 0.05}
    joint_7: {trajectory: 0.05, goal: 0.05}
  stop_trajectory_duration: 0.5
  state_publish_rate: *loop_hz
  action_monitor_rate: *loop_hz

vel_arm_controller:
  type: velocity_controllers/JointTrajectoryController
  joints: *robot_joints
  gains:
    joint_1: {p: 100.0, i: 0.00, d: 0.0, i_clamp: 0.0}
    joint_2: {p: 100.0, i: 0.00, d: 0.0, i_clamp: 0.0}
    joint_3: {p: 100.0, i: 0.00, d: 0.0, i_clamp: 0.0}
    joint_4: {p: 100.0, i: 0.00, d: 0.0, i_clamp: 0.0}
    joint_5: {p: 100.0, i: 0.00, d: 0.0, i_clamp: 0.0}
    joint_6: {p: 100.0, i: 0.00, d: 0.0, i_clamp: 0.0}
    joint_7: {p: 100.0, i: 0.00, d: 0.0, i_clamp: 0.0}
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    joint_1: {trajectory: 0.05, goal: 0.05}
    joint_2: {trajectory: 0.05, goal: 0.05}
    joint_3: {trajectory: 0.05, goal: 0.05}
    joint_4: {trajectory: 0.05, goal: 0.05}
    joint_5: {trajectory: 0.05, goal: 0.05}
    joint_6: {trajectory: 0.05, goal: 0.05}
    joint_7: {trajectory: 0.05, goal: 0.05}
  stop_trajectory_duration: 0.5
  state_publish_rate: *loop_hz
  action_monitor_rate: *loop_hz

vel_group_arm_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints: *robot_joints
  gains:
    joint_1: {p: 100, i: 0.01, d: 10.0}
    joint_2: {p: 100, i: 0.01, d: 10.0}
    joint_3: {p: 100, i: 0.01, d: 10.0}
    joint_4: {p: 100, i: 0.01, d: 10.0}
    joint_5: {p: 100, i: 0.01, d: 10.0}
    joint_6: {p: 100, i: 0.01, d: 10.0}
    joint_7: {p: 100, i: 0.01, d: 10.0}

gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - gripper_joint_l
    - gripper_joint_r
  gains:
    gripper_joint_l: {p: 2000.0, i: 1, d: 20.0, i_clamp: 1}
    gripper_joint_r: {p: 2000.0, i: 1, d: 20.0, i_clamp: 1}
