arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - joint_7
  gains:
    joint_1:
      p: 2000
      d: 20
      i: 1
      i_clamp: 1
    joint_2:
      p: 2000
      d: 20
      i: 1
      i_clamp: 1
    joint_3:
      p: 2000
      d: 20
      i: 1
      i_clamp: 1
    joint_4:
      p: 2000
      d: 20
      i: 1
      i_clamp: 1
    joint_5:
      p: 2000
      d: 20
      i: 1
      i_clamp: 1
    joint_6:
      p: 2000
      d: 20
      i: 1
      i_clamp: 1
    joint_7:
      p: 2000
      d: 20
      i: 1
      i_clamp: 1
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    joint_1: {trajectory: 0.05, goal: 0.05}
    joint_2: {trajectory: 0.05, goal: 0.05}
    joint_3: {trajectory: 0.05, goal: 0.05}
    joint_4: {trajectory: 0.05, goal: 0.05}
    joint_5: {trajectory: 0.05, goal: 0.05}
    joint_6: {trajectory: 0.05, goal: 0.05}
    joint_7: {trajectory: 0.05, goal: 0.05}
  stop_trajectory_duration: 0.5
  state_publish_rate: 50
  action_monitor_rate: 10